# Generated by Django 3.1 on 2020-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='actual_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
